schema_version = "1.0.0"

id="threejs_gltf_previewer"
version="1.0.0"
name="THREE.js GLTF Previewer"
tagline= "Preview Blender models in THREE.js without the need of continuos exporting"
maintainer = "Zachary Van De Staey <zacharyplays2.0@gmail.com>"
type="add-on"

blender_version_min="4.0.0"
license=["SPDX:GPL-3.0-or-later"]
website = "https://github.com/ZacharyPlayss/blender-three-js-preview"