name: Build and Release Plugin

on:
  push:
    branches:
      - main

permissions:
  contents: write  

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  

      - name: Get version from manifest
        id: get_version
        run: |
          VERSION=$(grep -Po '^version\s*=\s*"\K[0-9]+\.[0-9]+\.[0-9]+' blender_manifest.toml)
          if [ -z "$VERSION" ]; then
            echo "Error: Could not extract version from blender_manifest.toml"
            exit 1
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Detected version: $VERSION"

      - name: Set up release folder
        run: |
          mkdir -p blenderThreePreview
          cp -r webserver blenderThreePreview/
          cp __init__.py blenderThreePreview/
          cp webserver.py blenderThreePreview/
          cp blender_manifest.toml blenderThreePreview/

      - name: Create ZIP archive
        run: zip -r blenderThreePreview.zip blenderThreePreview

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          files: blenderThreePreview.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
